spring:
  application:
    name: handcraftedboard
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/handcraftedboard?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password:

    jpa:
      show-sql: true
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          format_sql: true